import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import authStatsExtension from "./auth-stats.ts";
import bedrockExtension from "./bedrock.ts";
import budgetsExtension from "./budgets.ts";
import checkpointsExtension from "./checkpoints.ts";
import cliToolsExtension from "./cli-tools.ts";
import debugExtension from "./debug.ts";
import gitToolsExtension from "./git-tools.ts";
import helpExtension from "./help.ts";
import hooksExtension from "./hooks.ts";
import loginExtension from "./login.ts";
import measureTwiceExtension from "./measure-twice.ts";
import memoryExtension from "./memory.ts";
import pluginsExtension from "./plugins.ts";
import mcpExtension from "./mcp.ts";
import onboardExtension from "./onboard.ts";
import permissionsExtension from "./permissions.ts";
import repoStatusExtension from "./repo-status.ts";
import retroExtension from "./retro.ts";
import screenshotExtension from "./screenshot.ts";
import shareExtension from "./share.ts";
import watchExtension from "./watch.ts";
import mcpAdminExtension from "./mcp-admin.ts";
import oneLastPassExtension from "./one-last-pass.ts";
import permissionAdminExtension from "./permission-admin.ts";
import pluginAdminExtension from "./plugin-admin.ts";
import subagentsExtension from "./subagents.ts";
import themeExtension from "./theme.ts";
import todoExtension from "./todo.ts";
import usageExtension from "./usage.ts";

export default async function tcc(pi: ExtensionAPI): Promise<void> {
	bedrockExtension(pi);
	debugExtension(pi);
	cliToolsExtension(pi);
	gitToolsExtension(pi);
	screenshotExtension(pi);
	themeExtension(pi);
	usageExtension(pi);
	budgetsExtension(pi);
	memoryExtension(pi);
	todoExtension(pi);
	repoStatusExtension(pi);
	onboardExtension(pi);
	checkpointsExtension(pi);
	permissionsExtension(pi);
	permissionAdminExtension(pi);
	measureTwiceExtension(pi);
	subagentsExtension(pi);
	oneLastPassExtension(pi);
	hooksExtension(pi);
	helpExtension(pi);
	loginExtension(pi);
	authStatsExtension(pi);
	retroExtension(pi);
	shareExtension(pi);
	watchExtension(pi);
	const { mcpServers } = await pluginsExtension(pi);
	pluginAdminExtension(pi);
	await mcpExtension(pi, mcpServers);
	mcpAdminExtension(pi);
}
